# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hp2cfEnYUrBiJLl8p1B1GKR1I0E7f5j-
"""

from Particulas import *


"""Prueba para información del electrón  """
particles.Electrón.info()

"""Prueba para información de quark up  """
particles.Up.info()

